# Generated by Django 2.0.3 on 2018-03-19 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('marks', models.IntegerField(default=0)),
                ('standard', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='extra_curricular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('standard', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('board', models.CharField(max_length=30)),
                ('no_of_students', models.IntegerField()),
                ('no_of_facualty', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('no_of_parents', models.IntegerField(default=0)),
                ('parent_salary', models.IntegerField(default=0)),
                ('age', models.IntegerField()),
                ('handicapped', models.BooleanField(default=False)),
                ('no_of_siblingss', models.IntegerField(default=0)),
                ('school', models.CharField(max_length=30)),
                ('extra_curr', models.IntegerField(default=0)),
                ('std', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('marks', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='extra_curricular',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.Student'),
        ),
        migrations.AddField(
            model_name='acads',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.Student'),
        ),
    ]
