# Generated by Django 2.0.3 on 2018-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='cast',
            new_name='caste',
        ),
    ]
