# Generated by Django 2.0.3 on 2018-03-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='filter1_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='filter1_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='filter1_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='filter1_val',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='filter2_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='filter2_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='filter2_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='filter2_val',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='filter3_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='filter3_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='filter3_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='filter3_val',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='filter4_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='filter4_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='filter4_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='filter4_val',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='filter5_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='filter5_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='filter5_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='filter5_val',
            field=models.TextField(default=''),
        ),
    ]
