# Generated by Django 2.0.3 on 2018-03-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_auto_20180330_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='dash_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lists',
            name='dash_name',
            field=models.CharField(default='Unnamed Dashboard', max_length=1000),
        ),
        migrations.AlterField(
            model_name='graphs',
            name='dash_name',
            field=models.CharField(default='Unnamed Dashboard', max_length=1000),
        ),
    ]
