# Generated by Django 2.0.3 on 2018-03-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_auto_20180330_1149'),
        ('studentapp', '0003_useracces'),
    ]

    operations = [
    ]
