# Generated by Django 2.0.3 on 2018-03-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_auto_20180320_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergraphs',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='usergraphs',
            name='user',
        ),
        migrations.AlterField(
            model_name='graph',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='UserGraphs',
        ),
    ]
