# Generated by Django 2.0.3 on 2018-03-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_auto_20180320_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphs',
            name='user',
        ),
    ]
